generators/cloudfoundry/index.js, test/test-cloudfoundry.js
Renaming 'basic/' java generators to make the enable case more obvious
=> Rename 'basic' to 'enable' for clarity

generators/cloudfoundry/index.js
Move this initialization up to above the `manifestconfig` assignment, because it is overwriting some `env:` properties that I pass in the `server` object.
=> fix: manifest env

generators/cloudfoundry/index.js, generators/cloudfoundry/templates/pipeline_master.yml, test/samples/scaffolder-sample.js, test/test-cloudfoundry.js
This PR adds the final piece of functionality that **generator-swiftserver** needs in order to cut over to exclusively using **generator-ibm-cloud-enablement** for all Bluemix files.
As it currently stands, deployment using the deployment toolchain will fail on the first try in the *standalone use case*, as the services needed in the manifest and toolchain have not yet been created.  The command I have added here will account for this in a `bluemix.services` object, which is different from `bluemix.server.services` - the latter being an array of strings containing only the service instance names, which is insufficient for our use case.
This solution supports Swift at the current time, as it already leverages a `services` object using this format, Ultimately, we should reconcile this …
=> Pipeline create-service commands

generators/deployment/index.js
This is causing errors for generator-swiftserver as it may composeWith `deployment` only.
This problem won't show up if composeWith is used with `app` or one of the other subgenerators before `deployment`.
=> Fix handlebars require in deployment subgenerator

generators/kubernetes/index.js
generator-swiftserver may pass no domain in the bluemix.server object when generating certain types of project in the prompting flow.
=> Use default domain if not set

generators/deployment/index.js, generators/deployment/templates/container_build.sh, generators/deployment/templates/deploy_master.json, generators/deployment/templates/kube_deploy.sh, generators/deployment/templates/pipeline_master.yml, generators/deployment/templates/toolchain_master.yml, test/samples/deploy-stage-properties.yaml, test/test-deployment.js
Kube deploy job needs to have an `imagePullSecret` whose value is an image registry token to be able to pull images from image registry. When Kube cluster is created, there's no guarantee that this secret is automatically created and the token could be invalid.
=> Kube deploy takes in registry token and sets imagePullSecret

generators/deployment/index.js, package-lock.json, package.json
This prevents a file permissions error in CF deploy for Swift.
=> ignore .build-ubuntu

generators/kubernetes/templates/deployment.yaml, generators/kubernetes/templates/java/basedeployment.yaml, generators/kubernetes/templates/java/deployment.yaml, test/samples/deployment-with-mongo-java.yaml, test/samples/deployment-with-mongo.yaml
Needs double quotes around strings for replace function in Deployment.yaml,
else will fail helm lint. Remove version in selector, else won't be able
to make changes and upgrade deployed app because now the version label will
be different between new version and currently deployed version.
=> Fix Deployment.yaml to use correct quotes and remove version selector

generators/kubernetes/templates/deployment.yaml, test/samples/deployment-with-mongo.yaml
This is required in order to make helm install “—wait” flag to work
properly and wait until pods are actually ready.
=> Added rolling update strategy to kubernetes deployment.

generators/deployment/index.js, generators/dockertools/index.js, generators/dockertools/templates/python/Dockerfile, generators/dockertools/templates/python/manage.py, test/test-dockertools.js
`manage.py` exists to create a unified set of commands between python
projects. For Flask, it will make starting apps and running commands
easier locally and give an alternative to using `idt`. The run-commands
of several files have been updated to now integrate with `manage.py`.
=> feat: Added manage.py file for Python Starters

generators/deployment/index.js
`FLASK_DEBUG` should never be true when a user is deploying an app to
the cloud. The `manifest.yml` file is being updated appropriately.
(Note: With the introduction of `manage.py`, this should no longer make
a difference, but this is a fix that needs to be made anyway)
=> fix: Prevent python apps from deploying in debug mode

generators/kubernetes/index.js, generators/kubernetes/templates/deployment.yaml, generators/kubernetes/templates/python/prometheus/prometheus-config.yaml, generators/kubernetes/templates/python/prometheus/prometheus-deployment.yaml, generators/kubernetes/templates/python/prometheus/prometheus-service.yaml, test/samples/deployment-with-mongo.yaml, test/test-kubernetes.js
This PR adds additional charts to Flask Starter’s helm charts to
support the integration of a Prometheus Server to scrape the actual
starter as a remote pod/service.
=> feat: Adding Prometheus support for Kubernetes on Python Flask starters

generators/kubernetes/templates/basedeployment.yaml
Basedeployment had the same name as the deplpyment.  They must have different names.
=> fix: update basedeployment name

generators/kubernetes/templates/service.yaml, test/test-kubernetes.js
Add "-service" to the node service name for consistency across languages and add the name attribute "http" to the node service port that is required by Istio.
=> fix: node for istio support

generators/dockertools/templates/java/cli-config.yml.template
Fix bx dev build failure to build java app in Windows 10 Docker environment. Liberty test server fails to start if the server output directory is in the mapped in volume inside the Windows 10 Docker environment.
Signed-off-by: Patrick Tiu <tiu@ca.ibm.com>
=> fix(templates): Fix bx dev build failure for java app in Windows 10

generators/deployment/index.js
Pull request to escape the manifest command so that special characters can be allowed in swift projects.
=> fix: escape swift command

generators/kubernetes/index.js, generators/kubernetes/templates/swift/Jenkinsfile
Note that for this to work right now it's going to rely on [this](https://github.com/WASdev/microservicebuilder.lib/pull/69) PR.
Works by simply providing the Jenkinsfile if you're a Swift project in exactly the same way we do it for Node. In a Swift specific folder incase we want to add any overrides.
=> Add Jenkinsfile for Swift

generators/dockertools/templates/swift/Dockerfile-tools
Previously, if you tried to run the `tools-utils.sh debug` script from inside a shell in the docker container, it would prompt for sudo password, which the end user will not know b/c we don't set it in the tools container.    This change allows the debug script to execute the privileged `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope` command at any time in the container's lifecycle (not just as entry point/start command) without a disruptive prompt, and does not alter the security or features of the deploy container.
=> password no longer required for sudo in tools container

.editorconfig, generators/kubernetes/index.js, generators/kubernetes/templates/basedeployment.yaml, generators/kubernetes/templates/bindings.yaml, generators/kubernetes/templates/deployment.yaml, generators/kubernetes/templates/java/basedeployment.yaml, generators/kubernetes/templates/java/deployment.yaml, generators/kubernetes/templates/java/values.yaml, generators/kubernetes/templates/values.yaml, package-lock.json, test/test-kubernetes.js
Move service attributes (APM and Mongo) into a bindings.yml file (removes APM credentials from *deployment.yaml templates)
Use helm template commands to inline those credentials into the deployment.yaml at chart install time when a specific attribute is enabled (default is true)
Add tests for bindings.yaml, including verification of inlined attributes in rendered templates
resolves #275
=> Portability improvement

generators/dockertools/index.js
For swift server projects the executable name is no longer sanitized so that special characters and unicode is allowed. 
This means that if you generate a project with a special character the docker file generated [here](https://github.com/ibm-developer/generator-ibm-cloud-enablement/blob/a38d343fb30021a96cadd5f87e1a999d03ff23c9/generators/dockertools/templates/swift/Dockerfile#L35) does not match the path to your executable since it is sanitized in the file but not in the project.
Changing the path to be the bluemix name will correct this fault and make the dockerfile correct for the swift projects.
=> fix: remove santization on swift executable name

generators/dockertools/index.js, test/test-dockertools.js
Docker-compose and Docker-compose-tools was not using the same image names and container names that are in Dockerfile and Dockerfile-tools
=> fix(deployments): use same containerName and imageNames 

generators/dockertools/index.js
The cli-config file runs either `bmd-run-cmd` or `bmd-debug-cmd` after build is complete. In node, we need the dependencies and not just the production modules to run node starters that use webpack.
=> fix(deployment): remove production installation when running local/dev containers

generators/deployment/templates/kube_deploy.sh
https://github.ibm.com/arf/planning-languages/issues/300
Java starters deployed on kubes should actually be deploying correctly. The problem is the url that the logs print out is incorrect. It's grabbing the https port instead of the http port.
This PR fixes that--changing the `sed` regex from greedy to eager (grabbing the first port instead of second). Testing needs to be done for any starters that provide multiple ports.
=> fix: change kube_deploy to grab first port

generators/dockertools/templates/go/Dockerfile-tools
The $bx_dev_user variable was not translating due to having the wrong type of quotes around it in the last line of this file.
=> fix: typo wrong kind of quotes

generators/dockertools/templates/node/Dockerfile, generators/dockertools/templates/node/Dockerfile-tools
The template for the node generator has `node:8 `as base image in the generated dockerfiles. The `node:8`
image is based on the Debian "jessie" release, which is no longer supported for ppc64le and s390x architectures. So the apt-get update line in the generated dockerfiles now fails on those platforms, see
nodejs/docker-node#855. 
Fix is to update the base image to `node:8-stretch`, which uses the current stable debian release ("stretch", see https://www.debian.org/releases/)
Fix for https://github.com/ibm-developer/generator-ibm-cloud-enablement/issues/395
=> fix: move node base image up to 8-stretch

generators/dockertools/templates/java/Dockerfile.template, test/test-dockertools.js
Making a few changes so the APM config works correctly. There were a few issues:
1. the changes to server.env were not valid and likely never worked as expected. It relied on doing variable expansion which isn't supported in server.env
1. it didn't work with the Liberty container in non-root mode which is best practice
1. I'm suspicious of the -Xmx setting the heap to 728Mb. If the docker container has a smaller memory limit this will break.
To make this work I've put the server.env changes in as a docker env var and for the jvm args I've specified them using JVM_ARGS.
I haven't moved the -Xmx setting. I think it is probably better to set the heap usage to use a % of available memory. I think there is a way to do this, but I think this might make sense to put in the base image.
=> fix: Update the dockerfile apm config so it works correctly

generators/dockertools/templates/java/Dockerfile.template, test/test-dockertools.js
Duplicate of PR #414 (@NottyCode's pr) because devops not updated to handle forks yet.
=> fix: Remove apm tools from Liberty docker image

generators/deployment/index.js
Recently, Java and Swift generators have had tests fails because the domain property of the manifest is not passed through.
=> fix: domain properties not passed through

generators/dockertools/templates/java/Dockerfile.template
A prior change to remove APM also ended up removing the step that
installs any features in server config that are not in the base image
See bug #429
=> fix: Restore step to install missing features for server.

generators/dockertools/templates/swift/Dockerfile, generators/dockertools/templates/swift/Dockerfile-tools
This upgrades the version of Swift used in the base IBM Docker images from `4.2` to `4.2.1`.
=> fix: upgrade Swift version to 4.2.1

test/test-dockertools.js
A prior change to remove APM ( https://github.com/ibm-developer/generator-ibm-cloud-enablement/pull/414/files ) removed the usage and tests for installUtility.
The installUtility Dockerfile change was needed to install missing features for server  and was fixed here  https://github.com/ibm-developer/generator-ibm-cloud-enablement/commit/48233467cf7daf192a3807b4bf82b13c6e4e9ab1
This commit adds the test back to what it was before.
=> fix: Restore test to validate installUtility present

generators/dockertools/index.js, test/test-dockertools.js
Change cli-config.yml back to Dockerfiles, instead of compose yamls, until CLI can be changed to do the correct docker-compose command.
=> fix: Fix ic dev build for Node projects

generators/deployment/templates/pipeline_master.yml, test/samples/pipeline-kube-java.yml, test/samples/pipeline-kube-swift.yml, test/samples/pipeline-kube.yml
Pipeline environment properties that are expressions will no longer be supported by devops.  We need to revisit this mechanism to detect versions automatically, if it is still wanted.
=> removing expressions from env properties

generators/deployment/templates/kube_deploy.sh
By adding this code to the deploy script, we ensure that a cluster role binding is created before invoking `helm` commands.
See https://console.bluemix.net/docs/containers/cs_versions.html#cs_v112.
Closes #468 .
=> fix: add cluster role binding #468

generators/deployment/templates/pipeline_master.yml, test/samples/pipeline-cf-java.yml, test/samples/pipeline-cf-spring.yml, test/samples/pipeline-cf-swift.yml, test/samples/pipeline-cf.yml, test/samples/pipeline-kube-java.yml, test/samples/pipeline-kube-swift.yml, test/samples/pipeline-kube.yml
This change changes the [curl command](http://www.mit.edu/afs.new/sipb/user/ssen/src/curl-7.11.1/docs/curl.html) used by the Health Stage for Kubernetes and CF deployments.  The VSI check continues to use `-sL`.
Previously, the `-I` flags we used which sent a HEAD request to the application.  This was a problem for Swift applications, where the Health Stage failed with a 404 because Kitura does not currently process HEAD requests as GET requests, unlike other routers.  [This may change soon.](https://github.com/IBM-Swift/Kitura/issues/1414)
The solution in the meantime is to use the `-i` flag, which gets that header information in addition to the content from the GET request.  There is no impact of this change as we continue to grep the output of the curl command for the response code, so …
=> fix: health curl flag change

CHANGELOG.md, generators/deployment/templates/vsi_pipeline_master.yml, generators/vsi/templates/terraform/scripts/install_master.sh, package-lock.json, package.json, test/test-vsi.js, test/vsi-tmp/terraform/scripts/install.sh
Patched vsi deployment for java projects (outdated os/dependency)
> Patch is based on thread here: https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository
Fixed Node installation version
Fixes:
- https://github.ibm.com/arf/planning-languages/issues/795
- https://github.ibm.com/arf/planning-languages/issues/796
=> fix: java and node vsi installations were broken

CHANGELOG.md, generators/deployment/templates/vsi_pipeline_master.yml, package-lock.json, package.json
Moved `rsync` command out of java scope, so it runs for all language types in the `Deploy` stage
=> fix: missing rsync for non-java vsi templates

generators/deployment/index.js
The Go starter kits have been failing to deploy to CF recently, as the buildpack that they request used the legacy `cflinuxfs2` stack, while the current infrastructure defaults to `cflinuxfs3`.  I have updated this and removed the note about go_buildpack.  I am not certain whether the dependency support has changed, but making this change will fix the base case for the starter kits, and any service dependency issues can be addressed with #813.
=> fix: update buildpack for go

generators/dockertools/index.js, generators/dockertools/templates/cli-config-common.yml, generators/dockertools/templates/java/cli-config.yml.template, generators/dockertools/templates/spring/cli-config.yml.template, generators/lib/handlebars.js, package-lock.json, test/samples/scaffolder-sample-contents.js, test/test-dockertools.js
These changes allow for the `bluemix.applicationId` attribute to be rendered in the **cli-config.yaml** only when it is provided.  This is to assist the patterns workflow in the CLI.
=> fix: add app-id attribute for patterns flow

generators/deployment/index.js, generators/dockertools/index.js, generators/dockertools/templates/spring/cli-config.yml.template, generators/lib/utils.js, package-lock.json, package.json
This PR includes updates to files for Java pattern-types. We will be removing the following files from the static starter kits:
cli-config.yml
Dockerfile*
manifest.yml
Jenkinsfile <-- no longer need
/manifests/kube.deploy.yml <-- no longer needed
The first 3 files in the list will be generated dynamically when an app is created and when necessary will include the new app name in the artifacts. An exception in Spring, which has assets that are named after the `artifactId` from `pom.xml`. Included in this PR is a new Utils function that extracts the `artifactId` from `pom.xml` and assigns it where it's needed-- in Dockerfile and manifest.yml.
This PR also includes some defaults for Java that do not make it in generatorOptions in the case of static starter kits, like buildType and version.
=> Updated artifacts for pattern-type starter kits

generators/deployment/index.js, test/test-cloudfoundry.js
this workaround fixes the cf failures with the buildpack hitting the disk quota limit
=> fix(swift): update manifest with swift buildpack environment variable
