ibm-developer/generator-ibm-cloud-enablement

README.md
package-lock.json
package.json

Update master with change to add java metrics given javametrics options is passed in as true.

Dev to master

---

.nycrc
.travis.yml
README.md
package-lock.json
package.json
test/test-cloudfoundry.js
test/test-dockertools.js
test/test-kubernetes.js

This merge allows for post_build scripts and docker to work for javametrics (tobespc)

Merge Development into Master - allow post_build scripts

---

generators/cloudfoundry/templates/pipeline_master.yml
test/samples/post-build-script.txt

Added build_type `shell` to post_builder script and some other minor changes

updated post_builder script

---

test/test-cloudfoundry.js
test/test-dockertools.js

Clean up Java docker & cf tests

---

generators/kubernetes/index.js
generators/kubernetes/templates/java/service.yaml
test/test-kubernetes.js

Process service.yaml template with handlebars, to handle the condition for httpsPort

process service.yml template w/ handlebars

---

test/test-cloudfoundry.js
test/test-dockertools.js
test/test-kubernetes.js

Remove arrow functions. Mocha does not like them: 
https://mochajs.org/#arrow-functions

fix: remove arrow functions. mocha hates them

---

generators/cloudfoundry/index.js
test/test-cloudfoundry.js
test/test-dockertools.js

Signed-off-by: Kate Stanley <katheris@uk.ibm.com>

bugfix/SpringAppPath: Fix Spring app path in deployment files.

---

generators/cloudfoundry/index.js
test/test-cloudfoundry.js

Rename 'basic' to 'enable' for clarity

---

generators/kubernetes/index.js
generators/kubernetes/templates/java/istio.yaml
test/test-kubernetes.js

Adding istio.yaml file in the project root directory

add istio config file

---

package-lock.json
package.json

Merging changes for devops integration with CLI into master

---

generators/dockertools/templates/cli-config-common.yml

https://zenhub.innovate.ibm.com/app/workspace/o/arf/planning-localtools/issues/489

Added comments for cli-config.yml

---

generators/cloudfoundry/index.js
test/test-cloudfoundry.js

Signed-off-by: Kate Stanley <katheris@uk.ibm.com>

Add OPENAPI_SPEC env for Spring.

---

generators/dockertools/templates/spring/cli-config.yml.template
test/test-dockertools.js

Remove run command for Spring as it's now in the Dockerfile.
Signed off by : Adam Pilkington apilkington@uk.ibm.com

fix(templates): update cli-config.yml and associated test

---

generators/deployment/index.js
test/test-cloudfoundry.js

Signed-off-by: Kate Stanley <katheris@uk.ibm.com>

Update Spring swagger endpoint to /swagger/api.

---

generators/deployment/index.js

Change Java maven build command to skip the tests as no credentials are available during build yet.

Change build command to skipTests.

---

generators/deployment/index.js
package-lock.json
package.json

Update master branch with Java build command in pipeline that skips tests in maven

Update master with Java build command without tests

---

generators/dockertools/templates/java/Dockerfile.template
generators/kubernetes/templates/java/deployment.yaml
test/test-dockertools.js

1. Update /generators/dockertools/templates/java/Dockerfile.template to install and configure the APM data collector.
2. Update /generators/kubernetes/templates/java/deployment.yaml to set the APM server configurations
3. Update the /test/test-dockertools.js to verify the Dockerfile update correctly.
4. The test for deployment.yaml has been commented out, so not add the test to verify the Deployment.yaml

Integrate with APM Data Collector

---

generators/dockertools/index.js
generators/dockertools/resources/python/services.json
generators/dockertools/templates/python/Dockerfile
generators/dockertools/templates/python/Dockerfile-tools
test/test-dockertools.js

For app with PostgreSQL, a postgresql-dev binaries is required

Add custom Python package for PostgreSQL in Dockerfile.

---

generators/deployment/index.js
generators/deployment/templates/pipeline_master.yml
test/samples/pipeline-kube-swift.yml
test/test-deployment.js

This change adds logic in the `pipeline.yml` script to stitch together the Swift tools dockerfile, compilation command, and runtime image dockerfile, using multistage builds in docker.

fix: swift kubernetes

---

generators/dockertools/templates/spring/Dockerfile.template

update Spring Dockerfile to FROM ibmjava:8-sfj-alpine

update Spring Dockerfile to FROM ibmjava:8-sfj-alpine

---

generators/kubernetes/templates/basedeployment.yaml
generators/kubernetes/templates/java/basedeployment.yaml
test/test-kubernetes.js

add test case for the basedeployment and some fixes in basedeployment

fix:add test and update basedeploy

---

generators/app/index.js

Signed-off-by: Katherine Stanley <katheris@uk.ibm.com>

fix(prompt): Fix prompting so chosen options are used in generation

---

generators/dockertools/templates/java/Dockerfile-tools.template
generators/dockertools/templates/java/cli-config.yml.template
generators/dockertools/templates/spring/Dockerfile-tools.template
generators/dockertools/templates/spring/Dockerfile.template
generators/dockertools/templates/spring/cli-config.yml.template

https://github.ibm.com/arf/planning-java/issues/345

feat: Move to cli-config version 0.0.3

---

generators/dockertools/templates/java/cli-config.yml.template

Signed-off-by: Patrick Tiu <tiu@ca.ibm.com>

fix(templates): Fix mvn install command in Java cli-config yml file

---

generators/dockertools/templates/python/Dockerfile
generators/dockertools/templates/python/Dockerfile-tools
generators/dockertools/templates/python/manage.py

fix: fixed FLASK_APP variable and added support for run-dev script

---

generators/dockertools/templates/python/Dockerfile

chore: fixed Django worker timeout with gunicorn

---

generators/dockertools/templates/python/manage.py

fix: change shell commands and port num

---

CHANGELOG.md

resolves #251. 0.12.1 release does not exist in npm

Correct version mismatch (no semver change)

---

generators/dockertools/index.js

https://github.ibm.com/arf/planning-node/issues/486

fix: changed the node debug port form 5858 to 9229

---

generators/dockertools/templates/java/Dockerfile-tools.template
generators/dockertools/templates/java/Dockerfile.template
generators/dockertools/templates/node/Dockerfile-tools
generators/dockertools/templates/spring/Dockerfile-tools.template
generators/dockertools/templates/spring/Dockerfile.template
generators/dockertools/templates/swift/Dockerfile
generators/dockertools/templates/swift/Dockerfile-tools

This PR resolves Issue #267 and PR #268

fix: update image to install bc and remove deprecated MAINTAINER flag

---

generators/dockertools/index.js
generators/dockertools/templates/cli-config-common.yml
generators/dockertools/templates/node/Dockerfile
test/test-dockertools.js

* Adding missing additional mounts in cli-config for node
* Added more validation to check dockerfile-run and dockerfile-tests

fix(deployment): added validation for dockerfiles in code and impl and added missing comps in node

---

generators/deployment/templates/pipeline_master.yml
generators/deployment/templates/toolchain_master.yml
package.json
test/samples/pipeline-kube-java.yml
test/samples/pipeline-kube-swift.yml
test/samples/pipeline-kube.yml
test/samples/toolchain-cf.yml
test/samples/toolchain-kube.yml
test/test-cloudfoundry.js

Updates structure for pipeline/deploy yaml files for open toolchain.  
- Fixes https://github.ibm.com/arf/planning-languages/issues/245
- Fixes https://github.ibm.com/arf/planning-languages/issues/229

updated to open toolchain version '2' structure yamls

---

generators/deployment/index.js
generators/deployment/templates/vsi_pipeline_master.yml
test/test-vsi.js
test/vsi-tmp/debian/install

fix(vsi): added template variable for health endpoint

---

generators/deployment/templates/kube_deploy.sh

fix: polling helm version for Tiller pod to become active on new kube cluster

---

generators/deployment/templates/vsi_pipeline_master.yml

Added logic to fetch service credentials for VSI deployments for https://github.ibm.com/arf/planning-codegen/issues/2036

added logic to fetch service credentials for VSI deployments

---

generators/deployment/index.js
generators/deployment/templates/deploy_master.json
generators/deployment/templates/pipeline_master.yml
generators/deployment/templates/toolchain_master.yml
test/samples/pipeline-cf-spring.yml
test/samples/pipeline-cf-swift.yml
test/samples/pipeline-cf.yml
test/samples/pipeline-cfee.yml
test/samples/toolchain-cf.yml
test/samples/toolchain-cfee.yml
test/test-cloudfoundry.js
test/test-deployment.js

2 things in this PR:
-- add hostname and domain as a form parameter for CF and CFEE. This is necessary for code patterns where we need unique hostname values.
-- add some CFEE support to toolchain generation. Some of this might not be necessary because our tests have been passing without it. But deploy.json at least should be used by toolchain validation and it looks like they don't do validation. If they start doing validation, we'll be covered.

Appname mustache

---

generators/dockertools/templates/swift/Dockerfile
generators/dockertools/templates/swift/Dockerfile-tools

This PR upgrades the produced Swift application to use [Swift 4.2.3](https://forums.swift.org/t/swift-4-2-3/21089).

chore: swift 4.2.3 support

---

test/samples/scaffolder-sample-contents.js

https://ibm.ent.box.com/file/436645088952

chore: fix for asoc compliance

---

generators/vsi/templates/terraform/main_master.tf

fix for https://github.ibm.com/arf/planning-languages/issues/852

renamed from bluemix to ibmcloud

---

generators/deployment/index.js
generators/deployment/templates/pipeline_master.yml
test/samples/pipeline-cf-java.yml
test/samples/pipeline-cf-spring.yml
test/samples/pipeline-cf-swift.yml
test/samples/pipeline-cf.yml
test/samples/pipeline-cfee.yml
test/test-cloudfoundry.js

fix: remove host and domain from CF toolchain

fix: remove host and domain from CF toolchain

---

generators/deployment/templates/kube_deploy.sh

removed deprecated -a parameter

fix: removed deprecated -a parameter

---

generators/deployment/templates/vsi_pipeline_master.yml
generators/vsi/templates/terraform/scripts/install_master.sh

1 fix for Blank Java VSI deployment
1 fix for Blank Django VSI deployment

fix: VSI issues

---

generators/dockertools/templates/swift/Dockerfile
generators/dockertools/templates/swift/Dockerfile-tools

Originally opened in https://github.com/ibm-developer/generator-ibm-cloud-enablement/pull/560

chore: Rebase Dockerfiles on official swift:5.0.2 and swift:5.0.2-slim

---

generators/deployment/index.js
generators/deployment/templates/container_build.sh
generators/deployment/templates/pipeline_master.yml
generators/deployment/templates/toolchain_master.yml
test/samples/pipeline-kube-java-knative.yml
test/samples/pipeline-kube-java.yml
test/samples/pipeline-kube-knative.yml
test/samples/pipeline-kube-swift-knative.yml
test/samples/pipeline-kube-swift.yml
test/samples/pipeline-kube.yml
test/samples/toolchain-kube-knative.yml

Remove Helm install. Remove unneeded entries in toolchain and pipeline yamls.

feat: knative toolchain optimizations

---

.nycrc
generators/deployment/index.js
generators/deployment/templates/toolchain_master.yml
generators/functions/index.js
generators/functions/templates/toolchain_master.yml
test/samples/serverless-toolchain.yml
test/samples/toolchain-cf.yml
test/samples/toolchain-cfee.yml
test/samples/toolchain-kube-knative.yml
test/samples/toolchain-kube.yml

Removes backwards compatibility for the v1 endpoint which has been deprecated.

feat: remove v1 backwards compatibility

---

generators/kubernetes/index.js

fix: service.yml for knative deployment is now service.yaml to keep with best practices

fix service yaml

---

generators/kubernetes/templates/java/service.yaml
test/test-kubernetes.js

fix: changed java port order listing so that OTC External toolchains will pick the correct port to show the user

fix liberty
